config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # get 'tasks', to: 'tasks#index'
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/new', to: 'tasks#new', as: :new_task
  # get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # get 'tasks/:id', to: 'tasks#show', as: :task
  # patch 'tasks/:id', to: 'tasks#update'
  # delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :details %>
  <%= f.text_area :details, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :completed %>
  <%= f.check_box :completed, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit:
  <%= @task.title %></h1>

 <%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1 class="border-bottom">All Tasks</h1>
 <% @tasks.each do | task | %>
 <% if task.completed == true %>
  <p><i class="fa fa-check-square-o" aria-hidden="true"></i>
<%= link_to task.title, task%>
  <% else %>
    <i class="fa fa-square-o" aria-hidden="true"></i>
<%= link_to task.title, task%>

  <% end %>
  <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, task_path(task), method: :delete, data: { confirm: "Are you sure?" }%>
</p>
  <% end %>
<%= link_to 'Create Task', new_task_path, class: 'btn btn-primary'  %>

app/views/tasks/new.html.erb
<h1>Create a new Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1 class="d-inline"><%= @task.title %></h1>
<h2 class="d-inline"><%= link_to 'Edit this Task', edit_task_path, class: 'btn btn-primary'  %></h2>
<h3><%= @task.details %></h3>
<br>
<%= link_to 'Return to the list', tasks_path  %>